version: '3.7'
networks:
    laravel: null
services:
    nginx:
        image: 'library/nginx:stable-alpine'
        container_name: nginx-hotel-booking
        ports:
            - '8050:80'
        volumes:
            - './:/var/www/html'
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - php
            - mysql
        networks:
            - laravel
    mysql:
        image: 'library/mysql:5.7.22'
        container_name: mysql-hotel-booking
        restart: unless-stopped
        ports:
            - '3301:3306'
        volumes:
            - './mysql:/var/lib/mysql'
        networks:
            - laravel
        environment:
            MYSQL_DATABASE: hotel-booking
            MYSQL_USER: root
            MYSQL_PASSWORD: mysql879user17394787batU
            MYSQL_ROOT_PASSWORD: mysql879user17394787batU
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-hotel-booking
        volumes:
            - './:/var/www/html'
            - './storage/app/public/:/var/www/html/public/storage/'
            - './dockerphp/php.ini:/usr/local/etc/php/php.ini'
        ports:
            - '9900:9000'
        networks:
            - laravel
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:4.9.7'
        depends_on:
            - mysql
        networks:
            - laravel
        ports:
            - '30004:80'
        environment:
            - PMA_HOST=mysql-hotel-booking
            - PMA_PORT= 3306
        volumes:
            - /sessions
        container_name: phpmyadmin-hotel-booking

volumes:
    mysql:
        driver: local
